from src.config import CONFIGURATION
import subprocess
import os

def diff_gene_expression():
    '''Runs the R script diff_gene_expression.R to analyze a gene count matrix with the R library EdgeR. Passes the
    location of the count_output_dir as a command line argument. The  count_output_dir contains a gene count matrix
    generated by the subread and clean_counts modules.
    '''
    file_dir = os.path.dirname(__file__)
    subprocess.call(['Rscript', '{}/diff_gene_expression.R'.format(file_dir), CONFIGURATION['count_output_dir']])

def run():
    '''Runs the diff_gene_expression script.
    '''
    diff_gene_expression()
